name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build with Rollup
        run: npm run build

      - name: Prepare release asset
        run: cp dist/price-timeline-card.js price-timeline-card.js

      - name: Upload build to release
        uses: softprops/action-gh-release@v1
        with:
          files: price-timeline-card.js
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_PAT }}
